Feature/our number boleto
starkbank/sdk-python pull request #30
Opened 2020-09-22 22:18 UTC by vidalstark

2020-09-22 22:22 UTC, cdottori-stark requested changes

2020-09-22 22:22 UTC, cdottori-stark commented on CHANGELOG.md
> +- ourNumber attribute to Boleto
case errado

2020-09-23 00:06 UTC, vidalstark commented on CHANGELOG.md
> +- ourNumber attribute to Boleto
Resolvido

2020-09-27 16:44 UTC, cdottori-stark approved these changes

2020-09-27 16:45 UTC, merged