Add rules attribute to Transfer resource
starkbank/sdk-python pull request #89
Opened 2022-12-12 22:12 UTC by xavier-stark

2022-12-13 12:18 UTC, joaogpw-stark requested changes

2022-12-13 12:18 UTC, joaogpw-stark commented on README.md
> +You can also create transfers in the SDK (TED/Pix), and configure transfers behavior according to its rules.
Aqui não precisa da vírgula depois do and. Só coloca vírgula quando forem frases independentes.

2022-12-13 12:18 UTC, joaogpw-stark commented on starkbank/transfer/__transfer.py
> +    return parsed_rules
No Credit Note os métodos de parsing estão entre o init e os métodos (create ...) e não no final do arquivo. Não sei qual é o padrão mas seria bom deixar padronizado

2022-12-13 12:18 UTC, joaogpw-stark commented on starkbank/transfer/rules/__rule.py
> +    - resending_limit [integer, default 10]: Maximum number of retries if Transfer fails. It must be an integer between 0 and 10 ex: 5
Boa, eu tenho só fiquei em dúvida agora se isso é o numero de retentativas ou o numero de tentativas, vou esclarecer com o Matheus e te aviso

2022-12-13 13:43 UTC, joaogpw-stark requested changes

2022-12-13 13:43 UTC, joaogpw-stark commented on starkbank/transfer/__transfer.py
> +    - rules [list of Transfer.Rule, default None]: list of Transfer.Rule objects for modifying transfer behaviour. ex: [Transfer.Rule(resendingLimit=5)]
Não seria list of `Transfer.Rules`?

2022-12-13 13:45 UTC, joaogpw-stark commented on README.md
> +You can also create transfers in the SDK (TED/Pix), and configure transfers behavior according to its rules.
tranfers -> transfer

2022-12-13 22:18 UTC, joaogpw-stark requested changes

2022-12-13 22:18 UTC, joaogpw-stark commented on README.md
> +You can also create transfers in the SDK (TED/Pix) and configure transfers behavior according to its rules.
`and configure transfer behavior`

2022-12-13 22:18 UTC, joaogpw-stark commented on starkbank/transfer/__transfer.py
> +    - rules [list of Transfer.Rules, default None]: list of Transfer.Rule objects for modifying transfer behaviour. ex: [Transfer.Rule(key="resendingLimit", value=5)]
Tanto nas rules quanto nos tags acho que o padrão é mostrar o default da api, certo? O default dos dois seria uma lista vazia

2022-12-13 22:18 UTC, joaogpw-stark commented on starkbank/transfer/rules/__rule.py
> +
Tirar linha vazia

2022-12-13 22:18 UTC, joaogpw-stark commented on starkbank/transfer/rules/__rule.py
> +    The Transfer.Rule object modify the behavior of Transfer objects created in your Workspace.
The Transfer.Rule object modifies the behavior of Transfer objects when passed as an argument upon their creation.

2022-12-13 22:18 UTC, joaogpw-stark commented on tests/utils/transfer.py
> +import starkbank.transfer.rules.__rule
Mais bonito fazer:
`from starkbank.transfer import Rule`

2022-12-13 22:28 UTC, xavier-stark commented on starkbank/transfer/__transfer.py
> +    - rules [list of Transfer.Rules, default None]: list of Transfer.Rule objects for modifying transfer behaviour. ex: [Transfer.Rule(key="resendingLimit", value=5)]
Certo, deixei o padrão em lista vazia mesmo

2022-12-13 22:38 UTC, joaogpw-stark requested changes

2022-12-13 22:38 UTC, joaogpw-stark commented on README.md
> +You can also create transfers in the SDK (TED/Pix) and configure transfer behavior.
Pode colocar o `according to its rules`, eu tava mostrando a mudança mesmo

2022-12-14 16:42 UTC, cdottori-stark commented on README.md
> +              key="resendingLimit",  # Set maximum number of retries if Transfer fails.
melhor falar que é se falhar por falhas sistêmicas no banco recebedor

2022-12-14 17:22 UTC, cdottori-stark approved these changes

2022-12-14 17:22 UTC, merged