Add DynamicBrcode resource
starkbank/sdk-python pull request #92
Opened 2023-01-06 17:31 UTC by xavier-stark

2023-01-06 20:35 UTC, joaogpw-stark requested changes

2023-01-06 20:35 UTC, joaogpw-stark commented on starkbank/dynamicbrcode/__dynamicbrcode.py
> +    - amount [integer]: DynamicBrcode value in cents. Minimum = 1 (any value will be accepted). ex: 1234 (= R$ 12.34)
Aqui o mínimo é 0

2023-01-06 20:35 UTC, joaogpw-stark commented on starkbank/dynamicbrcode/__dynamicbrcode.py
> +    - expiration [integer or datetime.timedelta, default 5097600 (59 days)]: time interval in seconds between due date and expiration date. ex 123456789
default é 3600

2023-01-06 20:35 UTC, joaogpw-stark commented on starkbank/dynamicbrcode/__dynamicbrcode.py
> +    - tags [list of strings]: list of strings for tagging
list of strings for tagging, will be passed to the reference Deposit resource when payed

2023-01-06 20:35 UTC, joaogpw-stark commented on starkbank/dynamicbrcode/__dynamicbrcode.py
> +    return rest.get_content(resource=_resource, id=id, size=size, user=user, sub_resource_name="png")
Vamos decidir na planing se adicionaremos ou não

2023-01-06 21:04 UTC, joaogpw-stark commented on starkbank/dynamicbrcode/__dynamicbrcode.py
> +    - tags [list of strings]: list of strings for tagging, these will be passed to the reference Deposit resource when paid
faltou o default

2023-01-06 21:04 UTC, joaogpw-stark commented on starkbank/dynamicbrcode/__dynamicbrcode.py
> +    - tags [list of strings]: list of strings for tagging, these will be passed to the reference Deposit resource when paid
reference Deposit -> respective Deposit

2023-01-06 21:43 UTC, joaogpw-stark approved these changes

2023-01-10 13:54 UTC, joaogpw-stark requested changes

2023-01-10 13:54 UTC, joaogpw-stark commented on README.md
> +DynamicBrcodes doesn't have **due** date, keeping that in mind you cannot configure fine, fee, discounts and descriptions.
doesn't -> don't

2023-01-10 13:54 UTC, joaogpw-stark commented on README.md
> +When a DynamicBrcode is paid, a Deposit is created containing the DynamicBrcode’s uuid followed by "d" (d{uuid}) in the tags for conciliation.
`followed by` quer dizer que o `d` vêm depois, não antes

2023-01-10 13:54 UTC, joaogpw-stark commented on starkbank/dynamicbrcode/__dynamicbrcode.py
> +    When a DynamicBrcode is paid, a Deposit is created containing the DynamicBrcode's uuid in the tags for conciliation.
Faltou falar aqui que não é só a uuid

2023-01-10 15:54 UTC, xavier-stark commented on README.md
> +DynamicBrcodes doesn't have **due** date, keeping that in mind you cannot configure fine, fee, discounts and descriptions.
ok

2023-01-10 15:54 UTC, xavier-stark commented on README.md
> +When a DynamicBrcode is paid, a Deposit is created containing the DynamicBrcode’s uuid followed by "d" (d{uuid}) in the tags for conciliation.
ok

2023-01-10 15:54 UTC, xavier-stark commented on starkbank/dynamicbrcode/__dynamicbrcode.py
> +    When a DynamicBrcode is paid, a Deposit is created containing the DynamicBrcode's uuid in the tags for conciliation.
ok

2023-01-10 15:59 UTC, joaogpw-stark requested changes

2023-01-10 15:59 UTC, joaogpw-stark commented on README.md
> +### The differences between an Invoice and the DynamicBrcode are the following:
Acho que não precisa desse subtitulo no meio. Você já começou a desenvolver a ideia de diference ente ele e a Invoice na linha a cima, dai colocar um subtítulo e continuar em baixo com uma tabela fica esquisito

2023-01-10 15:59 UTC, joaogpw-stark commented on README.md
> +DynamicBrcodes don't have **due** date, keeping that in mind you cannot configure fine, fee, discounts and descriptions.
Discount e descriptions não têm a ver com duedate

2023-01-10 15:59 UTC, joaogpw-stark commented on README.md
> +When a DynamicBrcode is paid, a Deposit is created with the tags parameter containing the character “d” followed by the DynamicBrcode’s uuid (d{uuid}) for conciliation.
(d{uuid}) ->  "d{uuid}"

2023-01-10 16:05 UTC, joaogpw-stark approved these changes

2023-01-10 21:40 UTC, cdottori-stark approved these changes

2023-01-16 14:31 UTC, merged